version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Nz9hpXgD_
    ports:
    - 1433:1433
    volumes:
    - ./backup/ :/var/opt/mssql/backup